<a href="https://colab.research.google.com/github/suphalaksana/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np  #package สำหรับทำงานกับข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ matrix)

##Numpy Array มีกี่ dimensions ก็ได้

###สร้าง  numpy array

In [3]:
np_a = np.array([[1,2,3],[4,5,6]])  #สร้าง numpy array ที่มี 2แถว 3หลัก

In [4]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np_a.shape

(2, 3)

In [8]:
np_b = np.array([[1,4],[2,5],[3,6]])  #กำหนดแถว,หลัก
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

###matrix transpose กลับแถวเป็นหลักกลับหลักเป็นแถว

In [9]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

###สร้าง matrix เริ่มต้น(zeros,ones)

ค่าเริ่มต้นมี0 กับ 1

In [10]:
np_z = np.zeros((4,5))  #4แถว 5 คอลัมน์
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

###สร้าง matrix random

In [13]:
np.random.randn(5,5) #matrix 5*5 #random เอามาจาก normal distribution ที่มี nu = 0 std =1

array([[ 6.10473166e-01, -1.63246261e-01, -1.02551270e-01,
        -2.49541371e-01, -9.93829079e-02],
       [ 1.41506759e+00, -1.95198956e+00, -2.77494310e-01,
         8.90368457e-01,  2.18776473e+00],
       [ 7.14912982e-01,  8.24286238e-01, -1.98377342e-01,
         2.26219068e-04, -1.08521908e+00],
       [ 2.57779232e-01,  6.42949631e-02,  3.41635348e-01,
         2.98268546e-01, -2.84494979e-01],
       [ 3.10286002e-01,  8.11064155e-01, -1.23481465e+00,
        -4.19266293e-01, -7.39934518e-01]])

In [ ]:
2+